# Generated by Django 5.2.1 on 2025-05-27 09:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttestationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('10ky', '10 кю'), ('9ky', '9 кю'), ('8ky', '8 кю'), ('7ky', '7 кю'), ('6ky', '6 кю'), ('5ky', '5 кю'), ('4ky', '4 кю'), ('3ky', '3 кю'), ('2ky', '2 кю'), ('1ky', '1 кю'), ('1dan', '1 дан'), ('2dan', '2 дан'), ('3dan', '3 дан'), ('4dan', '4 дан'), ('5dan', '5 дан'), ('6dan', '6 дан'), ('7dan', '7 дан')], max_length=5, unique=True, verbose_name='Уровень')),
                ('order', models.PositiveIntegerField(help_text='Порядковый номер для сортировки (1 - самый низкий, 17 - самый высокий)', unique=True, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Уровень аттестации',
                'verbose_name_plural': 'Уровни аттестации',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название клуба')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Клуб',
                'verbose_name_plural': 'Клубы',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClubAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='dojoflow.club', verbose_name='Клуб')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Администратор клуба',
                'verbose_name_plural': 'Администраторы клубов',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+999999999'. До 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('workplace', models.CharField(blank=True, max_length=200, verbose_name='Место работы')),
                ('start_date', models.DateField(verbose_name='Дата начала занятий')),
                ('last_attestation_date', models.DateField(blank=True, null=True, verbose_name='Дата последней аттестации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='dojoflow.club', verbose_name='Клуб')),
                ('current_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='dojoflow.attestationlevel', verbose_name='Текущий уровень аттестации')),
            ],
            options={
                'verbose_name': 'Занимающийся',
                'verbose_name_plural': 'Занимающиеся',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата аттестации')),
                ('city', models.CharField(max_length=100, verbose_name='Место проведения (город)')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dojoflow.attestationlevel', verbose_name='Уровень аттестации')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestations', to='dojoflow.student', verbose_name='Занимающийся')),
            ],
            options={
                'verbose_name': 'Аттестация',
                'verbose_name_plural': 'Аттестации',
                'ordering': ['-date'],
                'unique_together': {('student', 'level')},
            },
        ),
    ]
