# Generated by Django 5.2.1 on 2025-06-04 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojoflow', '0002_alter_clubadmin_user_alter_clubadmin_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attestation',
            name='notes',
        ),
    ]
