# Generated by Django 5.2.1 on 2025-06-04 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojoflow', '0003_remove_attestation_notes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attestation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='attestation',
            name='level',
        ),
    ]
