# Generated by Django 5.2.1 on 2025-06-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoflow', '0004_remove_attestation_level'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attestation',
            unique_together={('date', 'city')},
        ),
        migrations.AddField(
            model_name='student',
            name='attestations',
            field=models.ManyToManyField(blank=True, related_name='participants', to='dojoflow.attestation', verbose_name='Участие в аттестациях'),
        ),
        migrations.RemoveField(
            model_name='attestation',
            name='student',
        ),
    ]
