# Generated by Django 5.2.1 on 2025-06-04 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojoflow', '0005_restructure_attestations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='last_attestation_date',
        ),
    ]
