# Generated by Django 5.2.1 on 2025-06-05 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoflow', '0006_remove_last_attestation_date_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='current_level',
        ),
        migrations.CreateModel(
            name='StudentAttestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('attestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attestations', to='dojoflow.attestation', verbose_name='Аттестация')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_attestations', to='dojoflow.attestationlevel', verbose_name='Полученный уровень')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attestations', to='dojoflow.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Участие в аттестации',
                'verbose_name_plural': 'Участия в аттестациях',
                'ordering': ['-attestation__date'],
                'unique_together': {('student', 'attestation')},
            },
        ),
    ]
