services:
  postgres:
    image: postgres:15
    container_name: dojoflow-postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: dojoflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dojoflow-network

volumes:
  postgres_data:
    driver: local

networks:
  dojoflow-network:
    driver: bridge 